apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vasyl-Pauk/argocd-nginx-devops-task.git
    targetRevision: main
    path: monitoring/loki-stack
    helm:
      chart: loki-stack
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 2.10.2
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

