apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-nginx-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vasyl-Pauk/argocd-nginx-devops-task.git
    targetRevision: main
    path: monitoring/prometheus-nginx-exporter
    helm:
      chart: prometheus-nginx-exporter
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 1.10.2
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

