grafana:
  enabled: true
  defaultDashboardsEnabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack.monitoring.svc.cluster.local:3100
      isDefault: false
      editable: true

alertmanager:
  enabled: false

